create table tb_worker (id int8 generated by default as identity, daily_income float8, name varchar(255), primary key (id));
INSERT INTO tb_worker(name, daily_Income) VALUES('Josevaldo Ramos', 350.0);
INSERT INTO tb_worker(name, daily_Income) VALUES('Persival Alfredo', 250.0);
INSERT INTO tb_worker(name, daily_Income) VALUES('Serafino Mendes', 300.0);
